### ISSUE TITLE
Production Readiness

### ISSUE THREAD

**Issue by viveceo** [gluesql/gluesql-js#1]
Hi,

Love this work. I was thinking of implementing the same exact thing. I had a few questions, would love to chat over the phone if you'd like.

(1) Have you done a benchmark comparison of this in comparison to common alternatives for state management? How does this compare to in memory Baobao, Redux, etc? Wasm is the future, but as of today, there are immense overheads. I am curious how fast this truly is and whether joining across 3 or 4 tables actually produces good performance in comparison to using normalized data.

(2) The storage layer seems to be a key value store as a hash map, what about transferring this into a blended hashmap / B+ tree akin to Baobao such that we can use normalized data and have the beauty of SQL (ie, JSONB)?

(3) Is there a way to hook in here through observables for state management? Ie, to your knowledge, can I listen to state changes in the database?

(4) Is there a way to hook into the SQL parser to implement custom logic? You forgot about one storage layer, remote :) I would like to add custom implementation here

Beautiful work, considering this for a huge project. Need to be thorough on new technology, and gage the founders insight. One of the questions I finish with is:

(5) If you were to bet your entire business on an application, would you do so with gluesql-js for the storage layer?

If so, I would be happy to contribute and not go with baobao which provides the ability to create a highly performant tree state

**Comment by panarch** [comment]
Hi, at first, I'm so glad that there is someone who I can share my thoughts, really.
Building Baobao and Redux like state management library over SQL database was the one of the main motivations to start this GlueSQL project.

Let's start with answering your questions.

> (1) Have you done a benchmark comparison of this in comparison to common alternatives for state management? How does this compare to in memory Baobao, Redux, etc? Wasm is the future, but as of today, there are immense overheads. I am curious how fast this truly is and whether joining across 3 or 4 tables actually produces good performance in comparison to using normalized data.

No, I haven't yet. Now gluesql-js is just on demonstration stage. I'd really like to make something over this in the future, but now there are still lots of prior works to do on main repo `gluesql` so I'm mainly focusing on that.
But I don't think performance can be any issue.

* Performance downgrade by compilation from native to wasm.

It is now usually less than twice, it can be still quite better than native javascript.

* Joining multiple tables

This is all up to implementations, how big is state data, indexing, etc.
But even without any kind of optimization, I think it's capable enough to work for state management stuff.
This sort of performance can be issued when data grows more than 10,000 rows with multiple joins, then it is based on SQL database so we can still figure out how to solve but it can be quite tough using other state management libraries.

> (2) The storage layer seems to be a key value store as a hash map, what about transferring this into a blended hashmap / B+ tree akin to Baobao such that we can use normalized data and have the beauty of SQL (ie, JSONB)?

Index is planned to implement, but current GlueSQL does not have index support.
SQL queries should run both with and without index, so current storage implementation you can see is without supporting index.
It can be inefficient on handling large dataset.
After GlueSQL provides index feature and when GlueSQL-js consider to implement storage layer, extra work will be required.

> (3) Is there a way to hook in here through observables for state management? Ie, to your knowledge, can I listen to state changes in the database?

It actually depends on storage layer.
Current storage implementation does not provide observable functions but you can consider to make yourself.
It would be also very cool to have this feature in GlueSQL, but no plan for now.

> (4) Is there a way to hook into the SQL parser to implement custom logic? You forgot about one storage layer, remote :) I would like to add custom implementation here

Implementing custom storages are always welcome and I'd like to provide supports as much as I can.
GlueSQL dependes on https://github.com/ballista-compute/sqlparser-rs and it is ok to partially modify this.
And exeucution layer is fully implemented in gluesql project.

> (5) If you were to bet your entire business on an application, would you do so with gluesql-js for the storage layer?

Very interesting question, I'm currently maintaining GlueSQL project and it is in very early stage so there exists lots of work to do.
But at the same time, working on GlueSQL itself cannot make money for now so I need to do something else for keeping this kind of work.
I'm now starting to consider making something using GlueSQL but nothing decided yet.

---
If I can know more context about your status, I think we can find our shared goal which works both of us well.
Your current work, how much effort you're considering to spend, etc.

Using this thread or chat both works well.
If you want to keep conversion over talk, please let me know when & what time do you prefer.
fyi. I'm living in Seoul, Korea - KST (UTC +9h).

**Comment by viveceo** [comment]
Thank you for the thoughtful reply – we have much in common in our inspirations.

I am building a novel commerce platform. I needed a repeatable, very fast approach to development as maximizing time on investment is so important when going against the giants. In doing so, I discovered an interesting, new way to program the front-end which is to conform the access of all state layers to an extension of SQL. This helps reduce time of development time tenfold. More specifically, I have a custom executor in between the data layer and the view layer.

Here are sample queries:

SELECT header FROM local::cache/collection/designer WHERE id = '124124124'

This accesses a local cache which conforms to a N-Ary Tree akin to a zipper tree / property tree, and it plucks the 'header' property out of the object

SELECT * FROM remote::http::get/compute/collection WHERE params = 'id=${id}' and body = ${cursor}

This accesses remote endpoints which conforms to http get, you can use websockets, gRPC, etc.

SELECT * FROM local::db/collection JOIN local::db/entity ON parent_id = id WHERE id = ${id}

This accesses a local db named collection and a local db named entity

SELECT sales(price) FROM remote::shopify::product WHERE id = ${id}

This accesses a remote shopify product from their api and gets its sales price

Overall, this entirely separates all of the view logic and state logic and encapsulates everything into a single programming language that can be recyclable across mobile, web, anywhere. A lot more nitty gritty details here, but I call it the meta os: https://vitruvius.medium.com/runtime-compile-time-automation-commoditizing-the-lucrative-task-of-software-creation-436680e61cce

I am looking at using your solution to create a state tree in web, since it is very similar to SQL Lite where my mobile app keeps most of state.

I am looking at pairing it potentially with custom Baobao implementation so that I can cache view states

Happy to chat over message. I am living in Seattle and can talk anytime. I too, have a day job :)

**Comment by panarch** [comment]
> I am looking at using your solution to create a state tree in web, since it is very similar to SQL Lite where my mobile app keeps most of state.

Awesome.

By the way,
```sql
SELECT * FROM local::db/collection JOIN local::db/entity ON parent_id = id WHERE id = ${id}
```
This sounds like... you're also considering to join across databases?, like this below
```sql
SELECT * FROM local::db/collection JOIN remote::http::get/entity ON parent_id = id WHERE id = ${id}
```

and I also sent you an email to vitruvius@clubvive.io
Let's keep talk about this :)
